#!/usr/bin/env ruby

require "optparse"
require "methadone"
require "json"
require "fileutils"
require "pathname"
require "double/space.rb"

class App
  include Methadone::Main
  include Methadone::CLILogging


  main do
    story = Double::Space.story(".")
    if story.exists?
      if options["act"] && options["scene"]
        act   = options["act"].to_i
        scene = options["scene"].to_i

        story.new_scene!(act,scene)
      elsif options["act"] || options["scene"]
        exit_now! "You must specify both --act and --scene or neither"
      else
        clean = options["clean"]
        formatted_story = story.formatted(annotations: !options["clean"])
        formatted_story.generate("story.hml")
      end
    else
      puts "Initializing project..."
      story.create!
      puts "New project setup.  Get writing!"
      puts "Re-run `ds` to generate your story"
    end
  end

  on("--[no-]clean", "Produce a clean HTML version with no notes or metadata")
  on("--manuscript", "Produce a .docx file that contains a hopefully properly formatted manuscript you can submit")
  on("--real-italics", "Use real italics in the manuscript and not underlines")
  on("-a ACT", "--act", "Create a new empty scene in act ACT", /^\d+$/)
  on("-s SCENE", "--scene", "Create a new empty scene in act ACT", /^\d+$/)

  version Double::Space::VERSION

  use_log_level_option :toggle_debug_on_signal => 'USR1'

  description "Write and submit your amazing short story"

  go!
end
