#!/usr/bin/env ruby

require 'optparse'
require 'methadone'
require 'double/space.rb'

class App
  include Methadone::Main
  include Methadone::CLILogging

  main do
  end

  on("--[no]-clean", "Produce a clean HTML version with no notes or metadata")
  on("--manuscript", "Produce a .docx file that contains a hopefully properly formatted manuscript you can submit")
  on("--real-italics", "Use real italics in the manuscript and not underlines")

  version Double::Space::VERSION

  use_log_level_option :toggle_debug_on_signal => 'USR1'

  description "Write and submit your amazing short story"

  go!
end
